---
name: Push
on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
jobs:

  push:
    runs-on: ubuntu-latest
    steps:

      # Install golang
      - uses: actions/setup-go@v2
        with:
          go-version: 1.20.0
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DNAME }}
          password: ${{ secrets.DPASS }}

      - name: Build and push go-runner image
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile
          platforms: linux/amd64
          tags: uditgaurav/locust:latest
